version: "3.8"

services:
  kaitos_app:
    container_name: kaitos_app
    image: kaitos_app
    command: "npm run dev"
    build:
      context: ./
      dockerfile: /dockerfiles/app/Dockerfile
    restart: unless-stopped
    volumes:
      - ./kaitos/src:/var/www/src
    ports:
      - 3000:3000
    networks:
      - net

networks:
  net:
    driver: bridge